FullStackWithLawrence/aws-openai

.mergify.yml
README.md
SEMANTIC_VERSIONING.md

- [ * ] Documentation
add contributor commit comment guidelines

Test CI automation for pull requests

---

.github/workflows/pythonTests.yml

- have to add a .env file to the root of the repo and initialize so that test environment matches prod

fix: add a .env file to root so that test environment matches prod

---

.github/workflows/pythonTests.yml

- [ * ] Chore
bump actions versions and remove pip path dump

chore: bump actions package versions and remove dump of pip path

---

api/terraform/endpoint/mapping-templates/openai-integration.tpl
api/terraform/python/layer_genai/openai_utils/utils.py

- rebuild messages list from chat_history when it exists.

refactor: add chat_history to lambda event and rebuild the messages list

---

.github/dependabot.yml
client/src/components/chatApp/Component.jsx

- [ * ] Chore
- corrections and configuration improvements to dependabot config

dependabot configuration

---

.github/workflows/release.yml

- Fixes: don't persist credentials when calling actions/checkout
- always run Release when merging to main

fix: don't persist credentials when calling actions/checkout

---

.github/dependabot.yml
.github/workflows/mergeMainNext.yml
.github/workflows/testRelease.yml
SEMANTIC_VERSIONING.md

- [ * ] Chore
- add a workflow to propagate commits to from main to next

propagate commits to from main to next

---

.github/workflows/pushMain.yml
.github/workflows/testPreCommitRules.yml

- add GITHUB_TOKEN to semantic-release job

fix: add GITHUB_TOKEN to semantic-release job

---

.github/workflows/testPreCommitRules.yml
.github/workflows/testPullRequest.yml

- move pre-commit rule checking to a standalone workflow

refactor pre-commit rule checking

---

.github/workflows/pushMain.yml
.github/workflows/semanticVersionBump.yml

- [ * ] Chore
- use git merge --allow-unrelated-histories main

chore: use git merge --allow-unrelated-histories main

---

.github/workflows/pushMain.yml

- [ * ] Chore
- Fixes merge conflict

chore: add get fetch --all to each step

---

.github/workflows/pushMain.yml

chore: add a rebase and merge to main

---

.github/workflows/pushMain.yml

chore: fix up rebase push

---

.github/workflows/pushMain.yml

chore: try a rebase

---

.github/workflows/pushMain.yml

chore: use rebase on each step

---

.github/workflows/pushMain.yml

chore: try git merge -Xtheirs main

---

.github/actions/tests/pre-commit/action.yml
.github/actions/tests/python/action.yml
.github/actions/tests/reactjs/action.yml
.github/actions/tests/terraform/action.yml

- [ * ] Chore
- Add validations for local Github Actions

Add validations for local Github Actions

---

.github/actions/merge-branch/action.yml
.github/workflows/pullRequestController.yml
.github/workflows/pushMain.yml

- Add a dedicated merge-branch action

Add a dedicated merge-branch action

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/runTests.yml

- [ * ] Chore
- add a way to manually run tests

Add a way to manually run tests

---

.pre-commit-config.yaml
CHANGELOG.md
README.md
api/terraform/python/lambda_langchain/lambda_handler.py
api/terraform/python/lambda_langchain/tests/init.py
api/terraform/python/lambda_langchain/tests/test_01.py
api/terraform/python/lambda_openai/__init__.py
api/terraform/python/lambda_openai/tests/test_init.py
api/terraform/python/lambda_openai_v2/lambda_handler.py
api/terraform/python/lambda_openai_v2/tests/init.py
api/terraform/python/lambda_openai_v2/tests/test_01.py
api/terraform/python/layer_genai/openai_utils/__version__.py
api/terraform/python/layer_genai/openai_utils/const.py
api/terraform/python/layer_genai/openai_utils/setup_utils.py
pyproject.toml

- [ * ] Chore
- add more pre-commit hooks and relint repo

style: add more pre-commit hooks and relint repo

---

.github/dependabot.yml
api/terraform/python/layer_genai/openai_utils/__version__.py
codespell.txt
requirements.txt

- resolves breaking changes introduced in openai 1.x.x

fix: enable automated openai and langchain version bumps

---

README.md

Lint documentation

---

Makefile
api/README.md
api/terraform/python/layer_genai/openai_utils/__version__.py

- [ * ] Documentation
_Describe the testing that has been done or needs to be done_
_Add any relevant screenshots_
_List dependencies_
_Describe any breaking changes_

Update API setup docs for Pinecone

---

.github/workflows/precommitVersionBumps.yml

- have to git fetch so that we can see the 'next' branch when running job from main

chore: fix up git logic in new job

---

CONTRIBUTING.md
README.md

docs: rename so that 'contributing' will appear on github sidebar

---

.github/actions/tests/pre-commit/action.yml
.github/actions/tests/python/action.yml
.github/workflows/precommitVersionBumps.yml
.github/workflows/semanticVersionBump.yml

- [ * ] Chore
- performance enhancement for Github jobs that install npm/python packages

Cache npm and python dependencies

---

.github/actions/tests/pre-commit/action.yml
.github/actions/tests/python/action.yml
.github/workflows/precommitVersionBumps.yml
.github/workflows/semanticVersionBump.yml

chore: bump actions/cache to v3

---

Makefile

- Fixes .env initialization on Linux
- wrapped command in $()

refactor: .env initialization wasn't working in Linux

---

README.md

docs: add Python, NodeJS and Docker Compose to API requirements

---

.gitignore
CHANGELOG.md
README.md
api/terraform/python/layer_genai/openai_utils/__version__.py
openai.ipynb

chore: add a Jupyter Notebook with an example openai request

---

api/terraform/python/layer_genai/openai_utils/__version__.py
api/terraform/python/layer_genai/openai_utils/validators.py

- simulation for YouTube video

Simulated bug fix to record automated release process

---

README.md

_Describe the testing that has been done or needs to be done_
_Add any relevant screenshots_
_List dependencies_
_Describe any breaking changes_

chore: fix unit test badge link

---

.github/actions/tests/python/action.yml
.github/workflows/runTests.yml
.github/workflows/testsPython.yml
.gitignore
CHANGELOG.md
Makefile
api/postman/OpenAI.postman_collection.json
api/terraform/lambda_layer_pandas.tf
api/terraform/lambda_openai_function.tf
api/terraform/python/layer_nlp/README.md
api/terraform/python/layer_nlp/requirements.txt
api/terraform/python/layer_pandas/.gitignore
api/terraform/python/layer_pandas/Dockerfile
api/terraform/python/layer_pandas/README.md
api/terraform/python/layer_pandas/create_container.sh
api/terraform/python/layer_pandas/requirements.txt
api/terraform/python/openai_api/__version__.py
api/terraform/python/openai_api/common/conf.py
api/terraform/python/openai_api/lambda_openai_function/env.sh
api/terraform/python/openai_api/lambda_openai_function/function_refers_to.py
api/terraform/python/openai_api/lambda_openai_function/function_weather.py
api/terraform/python/openai_api/lambda_openai_function/lambda_config.yaml
client/src/components/chatApp/Component.jsx
requirements.txt

- [ * ] New feature
- add real-time 24 hour weather forecasting

add real-time 24-hour weather forecast to lambda_openai_function

---

.pre-commit-config.yaml
api/terraform/python/openai_api/common/tests/mock_data/json/passthrough_openai_v2_request.json
api/terraform/python/openai_api/common/tests/mock_data/json/passthrough_openai_v2_response.json
api/terraform/python/openai_api/common/tests/test_utils.py
api/terraform/python/openai_api/common/utils.py
api/terraform/python/openai_api/lambda_langchain/tests/mock_data/json/passthrough_langchain_request.json
api/terraform/python/openai_api/lambda_openai_function/lambda_config.yaml
api/terraform/python/openai_api/lambda_openai_function/tests/mock_data/json/mock_response.json
api/terraform/python/openai_api/lambda_openai_function/tests/mock_data/json/prompt_about_lawrence.json
api/terraform/python/openai_api/lambda_openai_function/tests/mock_data/json/prompt_about_recipes.json
api/terraform/python/openai_api/lambda_openai_function/tests/mock_data/json/prompt_about_weather.json
api/terraform/python/openai_api/lambda_openai_function/tests/test_lambda_openai_function.py
api/terraform/python/openai_api/lambda_openai_v2/tests/mock_data/json/passthrough_openai_v2_response.json
api/terraform/templates/test_200.json
client/src/components/chatApp/test/events/openai.response.v0.4.0.json
doc/json/apigateway_endpoint_airport_codes_result.json
doc/json/cloudwatch-apigateway-response-after-transformations.json
doc/json/cloudwatch-apigateway-response-before-transformations.json
doc/json/cloudwatch-lambda-response-dump.json
doc/json/openai.chat.completion.response.json

refactor test files: object is now object_type

---

README.md

_Describe the testing that has been done or needs to be done_
_Add any relevant screenshots_
_List dependencies_
_Describe any breaking changes_

refactor: create a dot-env template file

---

api/terraform/python/openai_api/__version__.py

_Describe the testing that has been done or needs to be done_
_Add any relevant screenshots_
_List dependencies_
_Describe any breaking changes_

chore: [gh] Update __version__.py to 0.11.0-alpha.1 [skip ci]
